build.gradle, src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Config/SwaggerConfig.java
=> [Feat] Swagger 설정하기

.gitignore, src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Token/Domain/Token.java, src/main/java/com/kwcapstone/Token/JwtTokenProvider.java, src/main/java/com/kwcapstone/Token/Service/TokenService.java, src/main/resources/application.properties
1. accesstoken 추가하기
2. Role 추가하기 
3. string 타입으로 socialId 변경하기
=> [Refactor] accesstoken 추가하기 및 Role 추가하기 및 String 타입으로 socialId 변경하기

src/main/java/com/kwcapstone/Service/MemberService.java
BaseException -> ResponseStatusException로 오류 리턴 방식 수정 (500에러만 뜨는 것에서 수정함)
=> fix: 오류 리턴 방식 수정

src/main/java/com/kwcapstone/Exception/AuthenticationException.java, src/main/java/com/kwcapstone/Exception/BadRequestException.java, src/main/java/com/kwcapstone/Exception/BaseException.java, src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java, src/main/java/com/kwcapstone/Repository/MemberRepository.java, src/main/java/com/kwcapstone/Security/JwtRequestFilter.java, src/main/java/com/kwcapstone/Security/PrincipalDetails.java, src/main/java/com/kwcapstone/Security/PrincipalDetailsService.java
1. JwtRequestFilter 구현하기
- jwt 토큰 추출하기
- jwt 유효한지 검사 절차 검증
- jwt 검증을 거치치 않아도 되는 것은 다로 빼두기
- jwt 검증 오류 시, response로 반환할 json 응답 생성 함수
2. principalDetails, principalDetailsService
- jwt 검증 이후, springcontext에 저장할 유저 정보를 가져오기 위함
- socialId로 찾기
=> [Refactor] security config 및 jwtrequestfilter 수정

src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/MemberLoginResponseDto.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
일반 로그인에서 JWT를 이상하게 사용하고 있어서 그 부분을 수정했습니다.
구글 로그인 중복 코드 부분을 수정했습니다.
close #31 
<br>
=> 31 refactor 일반 로그인 jwt 수정

src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Token/Service/TokenService.java, src/main/resources/application.properties
로그아웃에서 "예기치 않은 문제가 발생하였습니다" 문제를 해결하였습니다.
socialId -> objectId로 바꾸어서 사용자의 아이디를 추출할 수 있게 바꾸었습니다.
close #35 
<br>
=> 35 refactor 로그아웃 수정하겠습니다

src/main/java/com/kwcapstone/Common/BaseResponse.java, src/main/java/com/kwcapstone/Common/code/BaseCode.java, src/main/java/com/kwcapstone/Common/code/ResponseDTO.java, src/main/java/com/kwcapstone/Common/code/SuccessStatus.java, src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java, src/main/java/com/kwcapstone/Service/GoogleOAuthService.java, src/main/resources/application.properties
> kakao Login token 오류 고치기
> 문제 발생 시, 말씀 부탁드립니다.
> refactor #37 
<br>
=> [Refactor] kakao Login token 오류 고치기

src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Security/JwtRequestFilter.java, src/main/java/com/kwcapstone/Service/MemberService.java
구글 로그인에서 새로운 유저가 로그인 할 때에 약관 동의 페이지로 넘어가지 않는 문제를 해결하였습니다
close #39 
<br>
=> 39 refactor 구글 로그인 메서드 수정하겠습니다

src/main/java/com/kwcapstone/Common/BaseResponse.java, src/main/java/com/kwcapstone/Common/code/BaseCode.java, src/main/java/com/kwcapstone/Common/code/ResponseDTO.java, src/main/java/com/kwcapstone/Common/code/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/MemberLoginResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Kakao/Controller/KakaoController.java, src/main/java/com/kwcapstone/Kakao/Dto/KakaoResponse.java, src/main/java/com/kwcapstone/Kakao/Service/KaKaoProvider.java, src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Token/Controller/TokenController.java, src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
> Success Enum 추가(Error enum은 안 하기로 함)
> ResponseDto MemberId String 타입으로 변경
> 문제 발생 시, 말씀부탁드립니다.
> refactor #41 
<br>
=> [Refactor] Success Enum 추가 및 ResponseDto MemberId String 타입으로 변경

src/main/java/com/kwcapstone/Common/code/SuccessStatus.java, src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NoticeReadResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Domain/Entity/Notice.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java, src/main/java/com/kwcapstone/Repository/NoticeRepository.java, src/main/java/com/kwcapstone/Service/MainService.java, src/main/java/com/kwcapstone/Service/ProjectService.java
알림창 전체 조회 기능을 만들었습니다
1. 쿼리 파라미터 이용해서 알림 확인 유무 분류해서 보여주기
2. 최신순으로 정렬해서 보여줌
3. 모두 읽음도 처리할 수 있게 하기
close #45 
<br>
=> Feat/45 알림창 조회 기능 만들겠습니다

src/main/java/com/kwcapstone/Common/code/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NoticeDetailReadResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Notice.java, src/main/java/com/kwcapstone/Service/MainService.java
알림창 세부 조회 기능을 구현하였습니다 (1개씩 자세히 보기)
1. 알림의 세부 내용까지 볼 수 있게 하기
2. 세부 조회 기능으로 들어오면 isRead를 true로 바꿔서 저장하기
close #49 
<br>
=> Feat: 알림창 세부 조회 기능 구현

src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Domain/Entity/MemberToProject.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java
MemberToProject 엔티티를 추가하고, Project 엔티티의 record 부분과 script부분을 자체 클래스를 만들어서 수정하였습니다. (MongoDB의 JSON 형식 부분)
open #51
<br>
=> Refactor: MemberToProject 추가, Project 엔티티 수정

.github/workflows/gradle.yml, .gitignore, src/main/java/com/kwcapstone/Config/EmailConfig.java, src/main/resources/application.properties
cicd 파이프라인 구축을 위해 application.properties 파일 수정
open #53 
<br>
=> Ci/53 cicd 파이프라인 구축

.github/workflows/gradle.yml, Dockerfile
- 도커 관련 내용을 gradle.yml 파일에 추가하고, Dockerfile을 생성했습니다.
close #53 
<br>
=> Refactor: 도커 관련 내용 추가

src/main/java/com/kwcapstone/Common/code/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowRecordResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java, src/main/java/com/kwcapstone/Repository/MemberToProjectRepository.java, src/main/java/com/kwcapstone/Repository/ProjectRepository.java, src/main/java/com/kwcapstone/Service/MainService.java
녹음파일/녹음본 목록을 볼 수 있는 메인화면을 구현하였습니다.
close #51 
<br>
=> Feat/51 녹음파일 녹음본 메인화면 만들겠습니다

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowMainResponseDto.java, src/main/java/com/kwcapstone/Service/MainService.java
모든 회의 메인화면을 정렬 기준과, filterType에 따라 보여줍니다.
close #63 
<br>
=> Feat: 모든 회의 메인화면 기능 구현

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowSummaryResponseDto.java, src/main/java/com/kwcapstone/Service/MainService.java
요약본 메인화면을 sort와 filterType에 따라 리스트로 보여줍니다.
close #65 
<br>
=> Feat: 요약본 메인화면 기능 구현

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/PasswordRequestDto.java, src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Security/JwtRequestFilter.java, src/main/java/com/kwcapstone/Service/MemberService.java
> 비밀번호 변경 작업입니다.
> 기존 비밀번호와 변경할 비밀번호를 받습니다.
> 기존 비밀번호가 틀리면 비번 변경이 불가능하도록 로직이 되어있습니다.
> feat #61 
<br>
=> [Feat] 비밀번호 변경

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProfileResponseDto.java, src/main/java/com/kwcapstone/Service/MainService.java, src/main/java/com/kwcapstone/Service/MemberService.java
> 프로필 모달 조회입니다.
> 일반 유저들은 이미지를 등록하지 않는 이상 image가 null 로 뜹니다.
> feat #70
<br>
=> [Feat] 프로필 모달

src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
=> Refactor: 테스트 용으로 잠시 수정

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Controller/ConferenceController.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NewProjectResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java, src/main/java/com/kwcapstone/Repository/ProjectRepository.java, src/main/java/com/kwcapstone/Security/JwtRequestFilter.java, src/main/java/com/kwcapstone/Service/ConferenceService.java
새로운 프로젝트를 생성하는 기능입니다.
close #69 
<br>
=> Feat/69 회의 화면 프로젝트 생성 만들겠습니다

src/main/java/com/kwcapstone/Config/WebConfig.java
=> Refactor: 프론트 로컬 배포주소 추가

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ProfileEditRequestDto.java, src/main/java/com/kwcapstone/Domain/Entity/Member.java, src/main/java/com/kwcapstone/Service/MainService.java
> 프로필 수정입니다.
> 수정하고 싶은 필드(name, imageurl) 를 작성해서 api 보내주세요.
> 기존 내용과 같더라도 업데이트가 되었다고 뜨게 로직 처리 했습니다.
> feat #72 
<br>
=> [Feat] 프로필 수정

src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Service/MemberService.java
> 비번 변경하기
> 비번 변경하기입니다.
> 비번 암호화가 되어있지 않아서 이 부분이 진행된 후, 다시 refactor 해야 할 것 같습니다.
> refactor #82 
<br>
=> [Refactor] 비번 변경하기

src/main/java/com/kwcapstone/Controller/MemberController.java
>비번 변경 ci/cd 오류 고치기
> 없습니다.
>refactor #82 
<br>
=> [!Hofix] 비번 변경 ci/cd 오류 고치기

src/main/java/com/kwcapstone/Config/WebConfig.java
=> Refactor: 프론트.백엔드 배포주소 추가

src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Config/WebConfig.java
> 배포 오류 고치기
> refactor #91 
<br>
=> [Refactor] 배포 오류 고치기

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ProjectNameEditRequestDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameEditResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java, src/main/java/com/kwcapstone/Service/ProjectService.java
> 프로젝트 이름 수정하기
> projectId와 변경할 이름을 입력받음
> projectId 맞는 프로젝트를 찾아서 이름을 바꾸는 로직으로 진행
> projectId string 타입으로 받습니다.
> feat #93 
<br>
=> [Feat] 프로젝트 이름 수정하기

src/main/java/com/kwcapstone/Config/WebConfig.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ProjectDeleteRequestDto.java, src/main/java/com/kwcapstone/Repository/MemberToProjectRepository.java, src/main/java/com/kwcapstone/Service/ProjectService.java
프로젝트 삭제 기능을 구현하였습니다.
- 프로젝트를 선택해서 삭제할 수 있도록 합니다.
- 음성을 선택하면 음성만 지워집니다.
- 요약본을 선택하면 요약본만 지워집니다.
- 프로젝트를 선택하면 모든 게 지워집니다.
- 다중 선택을 해서 삭제하는 것도 가능합니다.
- 프로젝트에 연결된 사용자도 삭제 됩니다.
close #89 
<br>
=> Feat/89 프로젝트 삭제 기능 구현하겠습니다

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/GetProjectShareModalResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/MemberInfoDto.java, src/main/java/com/kwcapstone/Repository/InviteRepository.java, src/main/java/com/kwcapstone/Repository/MemberToProjectRepository.java, src/main/java/com/kwcapstone/Service/ProjectService.java
> 프로젝트 공유하기 모달 구현하기
> 내부적으로 초대 링크를 새로 생성하여 invitelink 생성함
> 참여자 목록을 구하기 위해서 MemberToproject 에서 Member 리스트를 가져옴
> 이를 memberInfo DTO 에 넣고 회의 생성자는 response 첫 번째에 나오도록 정렬 시킴
> Link랑 dto를 repsonse 에 넣고 반환함
> refactor 할 때 초대링크 구현하는 부분에서 조금 수정사항이 필요할 듯 합니다.
> 임시방편이라고 생각해주세요.
> feat #95 
<br>
=> [Feat] 프로젝트 공유하기 모달 구현하기

src/main/java/com/kwcapstone/Config/WebConfig.java
서버 도메인을 추가하였습니다.
close #102 
<br>
=> Refactor: 서버 도메인 추가

src/main/java/com/kwcapstone/Config/WebConfig.java
localhost:3000을 추가하였습니다.
close #102 
<br>
=> refactor: localhost 3000추가

.github/workflows/gradle.yml
=> Docs: gradle.yml 도커 관련 수정

src/main/java/com/kwcapstone/Config/WebConfig.java
=> Refactor: WebConfig 수정

src/main/java/com/kwcapstone/Config/WebConfig.java
=> Feat/102 https 리디렉션 기능 추가하겠습니다

src/main/java/com/kwcapstone/Config/SecurityConfig.java
spring config에도 cors 설정을 추가해주었습니다
<br>
=> Refactor: Security Config에 cors 설정 추가

src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Config/WebConfig.java
WebConfig의 내용을 SecurityConfig로 통합
<br>
=> Refactor: SecurityConfig로 통합

src/main/java/com/kwcapstone/Controller/MainController.java
api test에서 단순 텍스트가 아닌 상태 코드 반환하게 수정
<br>
=> Refactor: api test 상태 코드 반환하게 수정

src/main/java/com/kwcapstone/Security/JwtRequestFilter.java, src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
> accessToken 유효성 message 수정
> 없음
>  fix #117 
<br>
=> [Fix] accessToken 유효성 message 수정

build.gradle, src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Config/S3ClientConfig.java, src/main/java/com/kwcapstone/Config/WebSocketConfig.java, src/main/java/com/kwcapstone/Controller/ConferenceController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ScriptMessageRequestDto.java, src/main/java/com/kwcapstone/Service/ConferenceService.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Service/S3V3Service.java, src/main/java/com/kwcapstone/Service/S3V3ServiceImpl.java
=> Feat/115 스크립트 실시간 저장하겠습니다

src/main/java/com/kwcapstone/Naver/Service/NaverService.java, src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
> 로컬 테스트를 위한 accessToken validation time 수정
> 이를 위한 push
> 없음
> fix #123 
<br>
=> [Fix] security environment 수정

src/main/java/com/kwcapstone/Config/WebSocketConfig.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/InviteUsersByLinkResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameEditResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/SearchResponseWrapperDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowMainResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowRecordResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ShowSummaryResponseDto.java, src/main/java/com/kwcapstone/KwcapstoneApplication.java, src/main/java/com/kwcapstone/Repository/ProjectRepository.java, src/main/java/com/kwcapstone/Service/MainService.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Service/ProjectService.java
> main controller와 project Controller 에 response로 가는 모든 projectId 타입을 String으로 수정
> 없습니다.
> fix #129 
<br>
=> [FIX] projectid 를 string 타입으로 change

src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameEditResponseDto.java, src/main/java/com/kwcapstone/Service/MainService.java
>  filter & sort 수정
> fix #131 
<br>
=> [FIX] filter 수정

src/main/java/com/kwcapstone/Domain/Dto/Response/SearchResponseWrapperDto.java, src/main/java/com/kwcapstone/Service/MainService.java
검색했을 때 파일 이름 수정했습니다.
open #136 
<br>
=> Refactor: 검색했을 때 파일 이름 수정

src/main/java/com/kwcapstone/Config/JwtHandShakeInterceptor.java, src/main/java/com/kwcapstone/Config/WebSocketConfig.java
> webscocket과 jwt 연결
> 없음
> feat #135 
<br>
=> [Feat] webscocket과 jwt 연결

.github/workflows/gradle.yml, src/main/java/com/kwcapstone/Config/RoomParticipantTracker.java, src/main/java/com/kwcapstone/Config/WebSocketConfig.java, src/main/java/com/kwcapstone/Config/WebSocketEventListener.java, src/main/java/com/kwcapstone/Config/WebSocketSessionRegistry.java, src/main/java/com/kwcapstone/Controller/ConferenceController.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantRequestDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ParticipantResponseDto.java
참여자 이름/수 업데이트 기능입니다.
close #148 
<br>
=> Restore from 148

src/main/java/com/kwcapstone/Config/RoomParticipantTracker.java, src/main/java/com/kwcapstone/Config/WebSocketEventListener.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantDto.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantEventDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ParticipantResponseDto.java
참여자 수/이름 업데이트 수정합니다.
close #148 
<br>
=> Refactor: 참여자 수/이름 업데이트 수정

src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Service/ProjectService.java
- 이메일로 사용자 초대를 하는 기능에서 이메일 검사 로직을 추가합니다.
- 초대 수락 기능에 쿼리 파라미터를 추가합니다.
- 초대 수락 시 로그인이 되어있지 않다면 로그인을 하라는 경고를 띄웁니다.
close #152 
<br>
=> Refactor: 사용자 초대 기능, 초대 수락 기능 수정

build.gradle, src/main/java/com/kwcapstone/AI/GptConfig.java, src/main/java/com/kwcapstone/AI/GptController.java, src/main/java/com/kwcapstone/AI/GptDto.java, src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Config/JwtHandShakeInterceptor.java, src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Config/WebClientConfig.java, src/main/java/com/kwcapstone/Config/WebSocketConfig.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
>OpenApi 설정 완료
> GPT 설정 및 service 설정 완료
> GPT test를 위한 controller 완성
>gpt 라이브러리 사용하시는 분 gpt service 코드 참고해주세요
> feat #149 
<br>
=> [Feat] 실시간 요약 만들기

src/main/java/com/kwcapstone/Service/ProjectService.java
> invite url 변경하기
> accept -> add_by_link 로 변경
> feat #155 
<br>
=> [Refactor] invite url 변경하기

src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NewProjectResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/RecommendKeywordDto.java, src/main/java/com/kwcapstone/Service/ConferenceService.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
ObjectId를 String으로 리턴하도록 변경
<br>
=> Feat/147 추천 키워드 기능 만들겠습니다

src/main/java/com/kwcapstone/Service/ProjectService.java
> 공유 모달 url 고치기
>업슴
> feat #159 
<br>
=> [Refactor] 공유 모달 url 고치기

src/main/java/com/kwcapstone/AI/GptController.java, src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
> gpt service에 구현하기
> gpt controller 로 test 가능
> webSocket 도 구현 되어있습니다.
> 이슈로 추천 키워드라 해뒀는데 주요 키워드입니다!
> gptTest하면 string으로 넘어올겁니다! 이건 websocket으로 하면 변경되니 괜찮습니다!
<br>
=> [Refactor] 주요 키워드 5개 띄우기

src/main/java/com/kwcapstone/AI/GptController.java, src/main/java/com/kwcapstone/Controller/MainController.java
> 모달 띄우기에서 requestBody annotation 변경하기
> 모달 띄우기에서 requestBody annotation 변경하기
> fix #162 
<br>
=> [Refactor] 프로필 모달띄우기 수정

.github/workflows/gradle.yml
=> Refactor: 도커 수정

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/AuthPasswordCheckingRequestDto.java, src/main/java/com/kwcapstone/Service/MemberService.java
> 비번 동일한지 확인하기
> 비번 동일한지 확인하기
> feat #170 
<br>
=> [Feat] 비번 동일한지 확인하기

src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
=> 웹소켓 관련 jwt 수정

src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NodeSummaryResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NodeUpdateResponseDto.java, src/main/java/com/kwcapstone/Service/ConferenceService.java
> 노드간의 관계 설정
> summary 필드 변경
> script에 노드와 summary 같이 합쳐서 보내기
> 노드간의 관계 설정
> feat #183 
<br>
=> [Refactor] 노드간의 관계 설정

src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Service/ConferenceService.java
> positon 관련 정보도 프롬프트에서 받아오도록 수정 및 추출 코드 추가
> positon 관련 정보도 프롬프트에서 받아오도록 수정 및 추출 코드 추가
>refactor #185 
<br>
=> [Refactor] positon 관련 정보도 프롬프트에서 받아오도록 수정 및 추출 코드 추가

src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NodeUpdateResponseDto.java, src/main/java/com/kwcapstone/Service/ConferenceService.java
- 주요키워드/추천키워드 리턴을 수정했습니다.
- 마인드맵 오류 수정했습니다
- 요약본 오류 수정했습니다
close #188 
<br>
=> Refactor: 키워드 부분 리턴 수정

src/main/java/com/kwcapstone/Service/MemberService.java
> 비밀번호 초기화 에러 처리 추가하기
> 없음
> refactor #193 
<br>
=> [Refactor] 비밀번호 초기화 에러 처리 추가하기

build.gradle, src/main/java/com/kwcapstone/Config/S3Config.java, src/main/java/com/kwcapstone/Config/SecurityConfig.java, src/main/java/com/kwcapstone/Config/WebSocketConfig.java, src/main/java/com/kwcapstone/Config/WebSocketEventListener.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ParticipantResponseDto.java
참여자 이름/수 업데이트를 수정했슴다
회의화면에서 /topic으로 구독하고 participant_join으로 메시지를 보내면 회의방으로 들어올 수 있음
participant_leave로 메시지 보내면 회의방에서 나가집니다
participant_join하고 participant_leave로 메시지를 보내면 서버에서는 participants 이벤트로 참여자 이름/수를 보내줍니다
close #200 
<br>
=> Refactor/200 참여자 이름수 업데이트 수정

src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Service/ProjectService.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
클라이언트에서 서버로 stt 결과물을 보내면 서버는 로컬에 저장합니다.
> 이 PR과 연관된 이슈 번호를 작성하세요. close #202 
<br>
=> Refactor: 실시간 스크립트를 웹소켓으로 고침

src/main/java/com/kwcapstone/Config/SecurityConfig.java
> 프론트 임시 로컬 주소 추가
> "http://localhost:80", "http://localhost:3000:80" 추가해둠
> refacotr #207 
<br>
=> [Refactor] 프론트 임시 로컬 주소 추가

src/main/java/com/kwcapstone/Config/SecurityConfig.java
> 프론트 로컬 배포 주소 추가
>없음
> refactor #209 
<br>
=> [Refactor] 프론트 로컬 배포 주소 추가

src/main/java/com/kwcapstone/Config/SecurityConfig.java
> 프론트 로컬 접속 주소 수정
> 없음
> refactor #211 
<br>
=> [Refactor] 프론트 로컬 접속 주소 수정

src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/ProjectNameRequestDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/MainKeywordDtoResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameModifyResponseDto.java, src/main/java/com/kwcapstone/Domain/Dto/Response/SummaryResponseDto.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
> 요약본 웹소켓 함수 만들기
> 주요 키워드 웹소켓 함수 만들기
> 회의명 변경 controller 및 웹소켓 함수 만들기
> redis 설정 알아보다가 firebase가 더 비용측면으로 괜찮을 것 같아 고려 중에 있습니다. 추후 설정 완료 및 적용하겠습니다.
> refactor #206
<br>
=> [Refactor] 웹소켓으로 함수 변경

Dockerfile, src/main/java/com/kwcapstone/Domain/Dto/Request/MindmapAddRequestDto.java
=> Feat/218 마인드맵에 키워드 직접 추가

build.gradle, src/main/java/com/kwcapstone/AI/GptService.java, src/main/java/com/kwcapstone/Config/RedisConfig.java, src/main/java/com/kwcapstone/Controller/RedisController.java, src/main/java/com/kwcapstone/Service/WebSocketService.java, src/main/resources/application.properties
> websocket mainkeywords , script 등 문제발생
> redids 설정 주석처리 및 다시 git push
>fix #219 
<br>
=> [Fix] websocket mainkeywords , script 등 문제

src/main/java/com/kwcapstone/Service/ProjectService.java
> naver redirect url 수정
> naver redirect url 수정
> 수정된 url : http://localhost:3000/login/naver
> close #231 
<br>
=> [Bug] naver redirect url 수정

src/main/java/com/kwcapstone/Service/ProjectService.java
> 프로젝트 공유하기 목록 띄우기 inviteUrl 수정
> 테스트 이후 inviteUrl 은 배포 주소로 변경할 예정입니다.
> close #234 
<br>
=> [Refactor] 프로젝트 공유하기 목록 띄우기 inviteUrl 수정

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectStatusResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Project.java, src/main/java/com/kwcapstone/Service/ConferenceService.java, src/main/java/com/kwcapstone/Service/ProjectService.java
> 공유 링크 프로젝트 진행 상태 api 구현
> 없음
> close #236 
<br>
=> [FEAT] 공유 링크 프로젝트 진행 상태 api 구현

src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java, src/main/java/com/kwcapstone/Controller/ProjectController.java, src/main/java/com/kwcapstone/Service/ProjectService.java
> 프로젝트 공유 링크로 사용자 추가 구현 로직 중 변경된 로직 반영을 위해  invite code 를 없앰
> 없습니다.
> close #238 
<br>
=> [Refactor] 프로젝트 공유 링크로 사용자 추가 구현 수정

src/main/java/com/kwcapstone/Domain/Entity/Notice.java, src/main/java/com/kwcapstone/Service/ProjectService.java, src/main/resources/application.properties
리다이렉트 url 수정
리다이렉트 url 8080 -> 3000
<br>
=> Refactor: 이메일 고치는 중..

src/main/java/com/kwcapstone/Controller/WebSocketController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/SendProjectResponseDto.java, src/main/java/com/kwcapstone/Service/WebSocketService.java
> 스크립트 전송 웹소켓 추가
> close #250 
<br>
=> [Feat] 스크립트 전송 웹소켓 추가

src/main/java/com/kwcapstone/Controller/MainController.java, src/main/java/com/kwcapstone/Domain/Dto/Response/NoticeReadResponseDto.java, src/main/java/com/kwcapstone/Domain/Entity/Notice.java, src/main/java/com/kwcapstone/Service/MainService.java, src/main/java/com/kwcapstone/Service/MemberService.java, src/main/java/com/kwcapstone/Service/ProjectService.java
- Notice Entity 수정함 (url, official 추가)
- 알림 세부 조회 기능 삭제
- Notice Entity에서 content 삭제
<br>
=> Refactor Notice Entity 수정

src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/AgreementRequestDto.java, src/main/java/com/kwcapstone/Service/MemberService.java
구글로그인 -> 약관 동의 과정에서 세션 제거, 멤버아이디로 약관 동의할 수 있게 수정했습니다
<br>
=> Refactor: 구글 로그인, 약관 동의 수정

src/main/java/com/kwcapstone/Controller/MemberController.java, src/main/java/com/kwcapstone/Service/MemberService.java
=> Refactor 약관동의 202 오류 수정

src/main/java/com/kwcapstone/Service/GoogleOAuthService.java
=> Refactor 깃허브 액션 시크릿 수정

src/main/java/com/kwcapstone/Controller/ConferenceController.java, src/main/java/com/kwcapstone/Domain/Dto/Request/SaveProjectRequestDto.java, src/main/java/com/kwcapstone/Service/ConferenceService.java
> 누락된 status 파리미터 추가
> 누락된 status 저장 로직 추가
> close #259 
<br>
=> [Refactor] 누락된 파라미터 추가

src/main/java/com/kwcapstone/Service/ConferenceService.java
> saveProject 로그 추가
> close #265 
<br>
=> [Bug] saveProject 로그 추가
